#!/bin/bash

spinner() {
    local pid=$1
    local delay=0.1
    local spinstr='|/-\'
    while ps -p $pid > /dev/null; do
        local temp=${spinstr#?}
        printf " [%c]  " "$spinstr"
        local spinstr=$temp${spinstr%"$temp"}
        sleep $delay
        printf "\r"
    done
    printf "    \r"
}

echo "Starting build process..."

rm -rf dist

mkdir -p dist/Flowgorithm.app/Contents/MacOS
mkdir -p dist/Flowgorithm.app/Contents/Resources

echo "Downloading Flowgorithm executable... "
curl -L -s -o dist/Flowgorithm-exe-only.zip http://www.flowgorithm.org/download/files/Flowgorithm-exe-only.zip &
spinner $!

echo "Extracting files... "
unzip -q dist/Flowgorithm-exe-only.zip -d dist/Flowgorithm.app/Contents/MacOS &
spinner $!

rm dist/Flowgorithm-exe-only.zip

cp -r contents/ dist/Flowgorithm.app/Contents/

chmod +x dist/Flowgorithm.app/Contents/MacOS/Flowgorithm

echo "Build completed!"