#!/bin/bash

# Questo script crea un bundle Flowgorithm.app, aggiunge gli assets .exe di flowgorithm scaricati da http://www.flowgorithm.org/download/files/Flowgorithm-exe-only.zip e unzippali nella directory Contents/MacOS/ e aggiunge lo script di avvio "app"

rm -rf dist

mkdir -p dist/Flowgorithm.app/Contents/MacOS
mkdir -p dist/Flowgorithm.app/Contents/Resources

# Downloading latest Flowgorithm-exe-only.zip
curl -L -o dist/Flowgorithm-exe-only.zip http://www.flowgorithm.org/download/files/Flowgorithm-exe-only.zip
unzip dist/Flowgorithm-exe-only.zip -d dist/Flowgorithm.app/Contents/MacOS
rm dist/Flowgorithm-exe-only.zip

cp app dist/Flowgorithm.app/Contents/MacOS/Flowgorithm
chmod +x dist/Flowgorithm.app/Contents/MacOS/Flowgorithm

cp -r assets/ dist/Flowgorithm.app/Contents/Resources/

cp Info.plist dist/Flowgorithm.app/Contents/